/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FreeScreenSharingRouteImport } from './routes/free-screen-sharing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RRoomIdRouteImport } from './routes/r.$roomId'
import { Route as HostRoomIdRouteImport } from './routes/host.$roomId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeScreenSharingRoute = FreeScreenSharingRouteImport.update({
  id: '/free-screen-sharing',
  path: '/free-screen-sharing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomIdRoute = RRoomIdRouteImport.update({
  id: '/r/$roomId',
  path: '/r/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const HostRoomIdRoute = HostRoomIdRouteImport.update({
  id: '/host/$roomId',
  path: '/host/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/free-screen-sharing': typeof FreeScreenSharingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/host/$roomId': typeof HostRoomIdRoute
  '/r/$roomId': typeof RRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/free-screen-sharing': typeof FreeScreenSharingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/host/$roomId': typeof HostRoomIdRoute
  '/r/$roomId': typeof RRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/free-screen-sharing': typeof FreeScreenSharingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/host/$roomId': typeof HostRoomIdRoute
  '/r/$roomId': typeof RRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/free-screen-sharing'
    | '/sitemap.xml'
    | '/host/$roomId'
    | '/r/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/free-screen-sharing'
    | '/sitemap.xml'
    | '/host/$roomId'
    | '/r/$roomId'
  id:
    | '__root__'
    | '/'
    | '/free-screen-sharing'
    | '/sitemap.xml'
    | '/host/$roomId'
    | '/r/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreeScreenSharingRoute: typeof FreeScreenSharingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  HostRoomIdRoute: typeof HostRoomIdRoute
  RRoomIdRoute: typeof RRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-screen-sharing': {
      id: '/free-screen-sharing'
      path: '/free-screen-sharing'
      fullPath: '/free-screen-sharing'
      preLoaderRoute: typeof FreeScreenSharingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$roomId': {
      id: '/r/$roomId'
      path: '/r/$roomId'
      fullPath: '/r/$roomId'
      preLoaderRoute: typeof RRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/$roomId': {
      id: '/host/$roomId'
      path: '/host/$roomId'
      fullPath: '/host/$roomId'
      preLoaderRoute: typeof HostRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreeScreenSharingRoute: FreeScreenSharingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  HostRoomIdRoute: HostRoomIdRoute,
  RRoomIdRoute: RRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
